spring.application.name=DocuMind


server.port=8080

spring.datasource.url=jdbc:postgresql:-/localhost:5432/documind_db
spring.datasource.username=documind_user
spring.datasource.password=documind_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update # Use 'update' para desenvolvimento, 'validate' 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


openai.api.key=${OPENAI_API_KEY}
openai.base-url=https:-/api.openai.com/v1
openai.chat-model.name=gpt-4o 
openai.embedding-model.name=text-embedding-ada-002 
openai.timeout=60s

langchain4j.vector-store.pgvector.host=localhost
langchain4j.vector-store.pgvector.port=5432
langchain4j.vector-store.pgvector.database=documind_db
langchain4j.vector-store.pgvector.user=documind_user
langchain4j.vector-store.pgvector.password=documind_password
langchain4j.vector-store.pgvector.table-name=document_chunk 
langchain4j.vector-store.pgvector.dimension=1536 
langchain4j.vector-store.pgvector.create-table=true 
langchain4j.vector-store.pgvector.drop-table-on-startup=false 

spring.web.cors.enabled=true
spring.web.cors.allowed-origins=http:-/localhost:5173 
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true
spring.web.cors.max-age=3600